import './bootstrap';
import '../css/nav.css';
import '../css/about.css'
import '../css/skills.css'
import '../css/portfolio.css'
import '../css/services.css'
import '../css/testimonials.css'
import '../css/contact.css'
import '../css/backAbout.css'
import '../css/admin.css'